### ISSUE TITLE
Secure binding credentials breaks mysql plugin

### ISSUE THREAD

**Issue by menicosia** [andreasf/cf-mysql-plugin#11]
When service instances are deployed using secure binding credentials, the credentials are no longer available via `cf env` or even when `cf ssh` into a container:

```
$ cf env trivial-js
Getting env variables for app trivial-js in org system / space pivotal-services as admin...
OK

System-Provided:
{
 "VCAP_SERVICES": {
  "p.mysql": [
   {
    "binding_name": null,
    "credentials": {
     "credhub-ref": "/c/548966e5-e333-4d65-8773-7b4e3bb6ca97/52f2a8d2-e9d3-4358-8f00-6c5bd64f0d09/2dd37dff-35a2-4cf3-8acb-5ca760bef861/credentials"
    },
...
```

This causes the following sad behavior:

```
$ cf services
Getting services in org system / space pivotal-services as admin...

name       service   plan     bound apps   last operation
acceptDB   p.mysql   plan-1   trivial-js   create succeeded

$ cf mysql
No MySQL databases available. Please bind your database services to a started app to make them available to 'cf mysql'.
```

**Comment by menicosia** [comment]
@abg suggests we could go back to service keys?

```
$ cf create-service-key acceptDB marco-cli
$ cf service-key acceptDB marco-cli
Getting key marco-cli for service instance acceptDB as admin...

{
 "hostname": "10.0.8.5",
 "jdbcUrl": "jdbc:mysql://10.0.8.5:3306/service_instance_db?user=REDACTED\u0026password=REDACTED\u0026useSSL=false",
 "name": "service_instance_db",
 "password": "REDACTED",
 "port": 3306,
 "uri": "mysql://REDACTED:REDACTED@10.0.8.5:3306/service_instance_db?reconnect=true",
 "username": "REDACTED"
}
```
(It shows you the full credentials, I've substituted with REDACTED.)

**Comment by andreasf** [comment]
Hi Marco,

this is now implemented in master. The plugin creates a service key with name 'cf-mysql' for each service instance. A disadvantage is currently that it doesn't clean up after itself, deleting the keys is a necessary manual step before the service instance can be deleted.

Could you test it against a service broker with secure binding credentials?

**Comment by crhino** [comment]
@andreasf Tested with a broker using secure binding credentials and it works perfectly!

**Comment by andreasf** [comment]
Thanks for testing! 

I made a release to the plugin repository in the meantime.

@menicosia can this be closed?

**Comment by menicosia** [comment]
Yes, thank you!
