### ISSUE TITLE
 cf mysqldump debug-mysql (unable to get the dump, get ssh tunnel failed error)

### ISSUE THREAD

**Issue by deiveehan** [andreasf/cf-mysql-plugin#15]
Believe this requires ssh tunnelling enabled. Any thoughts on this / alternates on how to get this done. 

PROD Environment: cf mysqldump debug-mysql (unable to get the dump, get ssh error)

panic: SSH tunnel failed: Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

goroutine 58 [running]:
github.com/andreasf/cf-mysql-plugin/cfmysql.(*sshRunner).OpenSshTunnel(0xa9ac90, 0x879240, 0xc42016c370, 0x7ffc289d6ae3, 0x10, 0xc420204680, 0x3b, 0xc420166ef0, 0x4, 0xc420186f00, ...)
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/ssh_runner.go:25 +0x260
created by github.com/andreasf/cf-mysql-plugin/cfmysql.(*cfService).OpenSshTunnel
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/cf_service.go:61 +0x107

**Comment by deiveehan** [comment]
We prefer not to enable ssh in prod. any suggestions on how to do this would be great.

**Comment by andreasf** [comment]
You can always connect directly to your database, this plugin just attempts to make it more convenient.

If you created your database through a service broker, retrieve the credentials by [creating a service key](https://docs.cloudfoundry.org/devguide/services/service-keys.html). Then just connect with any MySQL client from a machine that can reach the DB over the network.

Alternatively, you could deploy another application that allows you to evaluate arbitrary SQL queries and bind the DB to it. I would not do that in a production environment though.
