### ISSUE TITLE
panic: SSH tunnel failed: Error: EOF

### ISSUE THREAD

**Issue by zmb3** [andreasf/cf-mysql-plugin#5]
I just downloaded v1.3.5 of the plugin and attempted to use it on one of my services:
```
❯ cf mysql my-service
panic: SSH tunnel failed: Error: EOF

goroutine 83 [running]:
panic(0x35a660, 0xc420498680)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/andreasf/cf-mysql-plugin/cfmysql.(*CfSshRunner).OpenSshTunnel(0x610b88, 0x56c0c0, 0xc420011dc0, 0xc4201a8510, 0xc, 0x0, 0x0, 0xc420127e60, 0x1c, 0xc4201a8b00, ...)
	/home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/ssh_runner.go:21 +0x254
created by github.com/andreasf/cf-mysql-plugin/cfmysql.(*CfServiceImpl).OpenSshTunnel
	/home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/cf_service.go:93 +0xc5
```

**Comment by andreasf** [comment]
Hi Zac,

thanks for reporting this issue. Is SSH access enabled for any of the apps in your space? (https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#check-ssh-permissions)

Can you successfully open a shell by running `cf ssh app-in-your-space`?

**Comment by zmb3** [comment]
This is on PWS.  I was able to `cf ssh` yesterday (it is enabled), but today I'm getting a similar error, so maybe this isn't related to the mysql plugin:

```
$ cf ssh my-app
FAILED
Error: SSH session allocation failed: EOF
```

**Comment by zmb3** [comment]
I can confirm this is not related to the plugin.  This error occurs when the app fails to start correctly.

Thanks for this great plugin - it's way easier than manually tunneling :-)
