### ISSUE TITLE
Feature request: work with a cf foundation with self-signed cert

### ISSUE THREAD

**Issue by eitansuez** [andreasf/cf-mysql-plugin#7]
currently i can't use cf mysql with a cf foundation that uses self-signed certs.  would be great if i could turn off certificate validation.  thanks.

**Comment by eitansuez** [comment]
i just noticed there appears to already exist a pull request for this.

**Comment by andreasf** [comment]
Hi! Thanks for reaching out. 

I just merged the PR and released 1.4.0. Until it's in the repository you can download it from the releases page.

It would be great if you could test the build and close this bug if it solved your issue.

**Comment by eitansuez** [comment]
hi andreas.  just tested.  works great with a cf instance with a self-signed cert.  thanks for the rapid turnaround!
